version: '3'

networks:
  mynw:

services:
  db:
    container_name: "pgdb"
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    networks: 
      - mynw

  app:
    container_name: "api"
    build: .
    depends_on:
      - "db"
    ports:
      - '3000:3000'
    volumes:
      - ./:/home/app
      - /home/app/node_modules
    networks:
      - mynw
